# INSERT ALUNO
INSERT INTO ALUNO VALUES(1,'CLAUDIA CAROLINE SOUSA DO CARMO','F','SOLTEIRO','PARTICULAR',33);
INSERT INTO ALUNO VALUES(2,'ERIK MEDEIROS BRANDAO','F','CASADO','PUBLICA',23);
INSERT INTO ALUNO VALUES(3,'HIGOR VINICIUS OLIVEIRA BARBOSA','F','SOLTEIRO','PUBLICA',25);
INSERT INTO ALUNO VALUES(4,'JAUSER PEREIRA DE MIRANDA JUNIOR','M','CASADO','PUBLICA',21);
INSERT INTO ALUNO VALUES(5,'JESSICA GABRIELA MOREIRA PETTI','F','SOLTEIRO','PARTICULAR',19);
INSERT INTO ALUNO VALUES(6,'JESSICA LINS DOS SANTOS','F','CASADO','PARTICULAR',10);
INSERT INTO ALUNO VALUES(7,'CARLA SANDIS DA SILVA','M','SOLTEIRO','PUBLICA',29);
INSERT INTO ALUNO VALUES(8,'ALCINA MERCIA VARJAO CARVALHO LIMA','M','SOLTEIRO','PUBLICA',26);
INSERT INTO ALUNO VALUES(9,'HIGOR VINICIUS OLIVEIRA BARBOSA','M','CASADO','PUBLICA',21);
INSERT INTO ALUNO VALUES(10,'JAUSER PEREIRA DE MIRANDA JUNIOR','F','SOLTEIRO','PARTICULAR',19);
INSERT INTO ALUNO VALUES(11,'JESSICA GABRIELA MOREIRA PETTI','F','CASADO','PARTICULAR',22);
INSERT INTO ALUNO VALUES(12,'JESSICA LINS DOS SANTOS','M','CASADO','PUBLICA',21);
INSERT INTO ALUNO VALUES(13,'ALCINA MERCIA VARJAO CARVALHO LIMA','M','SOLTEIRO','PARTICULAR',19);
INSERT INTO ALUNO VALUES(14,'BRUNO ALVES SILVA','M','CASADO','PUBLICA',21);
INSERT INTO ALUNO VALUES(15,'CLAUDIA CAROLINE SOUSA DO CARMO','F','SOLTEIRO','PARTICULAR',19);
INSERT INTO ALUNO VALUES(16,'CLAUDIA CAROLINE SOUSA DO CARMO','M','CASADO','PUBLICA',21);
INSERT INTO ALUNO VALUES(17,'CARLA SANDIS DA SILVA','F','SOLTEIRO','PARTICULAR',19);
INSERT INTO ALUNO VALUES(18,'ALCINA MERCIA VARJAO CARVALHO LIMA','M','CASADO','PUBLICA',21);
INSERT INTO ALUNO VALUES(19,'BRUNO ALVES SILVA','F','SOLTEIRO','PARTICULAR',19);
INSERT INTO ALUNO VALUES(20,'CARLA SANDIS DA SILVA','F','SOLTEIRO','PARTICULAR',19);

# INSERT ATIVIDADE
INSERT INTO ATIVIDADE VALUES(1,'LER MANUAL DE CONFIGURAÇÃO');
INSERT INTO ATIVIDADE VALUES(2,'CONFIGURAR AMBIENTE');
INSERT INTO ATIVIDADE VALUES(3,'LER MATERIAL DE APOIO');
INSERT INTO ATIVIDADE VALUES(4,'ASSISTIR VIDEO AULA');
INSERT INTO ATIVIDADE VALUES(5,'EXERCÍCIO PRÁTICO');
INSERT INTO ATIVIDADE VALUES(6,'AVALIAÇÃO');
INSERT INTO ATIVIDADE VALUES(7,'AVALIAÇÃO REC.');

# INSERT CURSO
INSERT INTO CURSO VALUES (1,'CIENCIA DA COMPUTAÇÃO- UFCG');

# INSERT NOS 